version: "3"
services:
  mongodb:
    image: "mongo:8.0.4"
    container_name: coredb-db
    ports:
      - "27017:27017"
  nginx:
    container_name: coredb
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3000:80"
  api:
    container_name: coredb-api
    build:
      dockerfile: Dockerfile.dev
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
  client:
    container_name: coredb-client
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
